# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='bookmark',
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserList',
        ),
    ]
