# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlsandbookmarks', '0003_remove_bookmark_clicks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='click',
            old_name='bookmark_clicked',
            new_name='bookmark',
        ),
    ]
