# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlsandbookmarks', '0005_auto_20160404_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
