# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlsandbookmarks', '0006_bookmark_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
