# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlsandbookmarks', '0008_auto_20160405_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='archived',
        ),
    ]
